# Generated by Django 4.1.7 on 2023-11-28 14:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dimension',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Nombre')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('weigh', models.FloatField(default=0, verbose_name='Peso')),
            ],
            options={
                'verbose_name': 'Dimensión',
                'verbose_name_plural': 'Dimensiones',
                'db_table': 'Dimension',
            },
        ),
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Nombre')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('weigh', models.FloatField(default=0, verbose_name='Peso')),
                ('dimension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Metrics.dimension')),
            ],
            options={
                'verbose_name': 'Indicador',
                'verbose_name_plural': 'Indicadores',
                'db_table': 'Indicator',
            },
        ),
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Nombre')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Variable',
                'verbose_name_plural': 'Variables',
                'db_table': 'Variable',
            },
        ),
        migrations.CreateModel(
            name='Scale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('scale_label', models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='Etiqueta')),
                ('initial_value', models.FloatField(verbose_name='Valor Inicial')),
                ('final_value', models.FloatField(verbose_name='Valor Final')),
                ('scale', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Metrics.variable')),
            ],
            options={
                'verbose_name': 'Escala',
                'verbose_name_plural': 'Escalas',
                'db_table': 'Scale',
            },
        ),
        migrations.CreateModel(
            name='MeasurementCriterion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Nombre')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('min_value', models.FloatField()),
                ('max_value', models.FloatField()),
                ('indicator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Metrics.indicator')),
            ],
            options={
                'verbose_name': 'Criterio de Medida',
                'verbose_name_plural': 'Criterios de Medida',
                'db_table': 'MeasurementCriterion',
            },
        ),
        migrations.AddField(
            model_name='dimension',
            name='variable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Metrics.variable'),
        ),
    ]
