# Generated by Django 4.1.7 on 2023-11-07 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Metrics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurementcriterion',
            name='max_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='measurementcriterion',
            name='min_value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
