# Generated by Django 4.1.7 on 2023-11-28 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Metrics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dimension',
            name='weigh',
            field=models.FloatField(default=1, verbose_name='Peso'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='weigh',
            field=models.FloatField(default=1, verbose_name='Peso'),
        ),
    ]
