# Generated by Django 4.1.7 on 2023-11-28 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Metrics', '0002_alter_dimension_weigh_alter_indicator_weigh'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variable',
            name='user',
        ),
    ]
