# Generated by Django 4.1.7 on 2023-11-16 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Metrics', '0003_alter_dimension_name_alter_indicator_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurementcriterion',
            name='max_value',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='measurementcriterion',
            name='min_value',
            field=models.FloatField(),
        ),
    ]
