# Generated by Django 4.1.7 on 2023-11-19 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Metrics', '0004_alter_measurementcriterion_max_value_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scale',
            name='interval',
        ),
        migrations.RemoveField(
            model_name='variable',
            name='scale',
        ),
        migrations.AddField(
            model_name='scale',
            name='final_value',
            field=models.FloatField(default=2, verbose_name='Valor Final'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scale',
            name='initial_value',
            field=models.FloatField(default=3, verbose_name='Valor Inicial'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scale',
            name='scale',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='Metrics.variable'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scale',
            name='scale_label',
            field=models.CharField(default=2, max_length=200, verbose_name='Etiqueta'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Interval',
        ),
        migrations.DeleteModel(
            name='Range',
        ),
        migrations.DeleteModel(
            name='ScaleLabel',
        ),
    ]
