# Generated by Django 4.1.7 on 2023-06-03 00:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Metrics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('answer', models.TextField(max_length=255, verbose_name='Respuesta')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Respuesta',
                'verbose_name_plural': 'Respuestas',
                'db_table': 'Respuesta',
            },
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=80, verbose_name='Nombre')),
                ('description', models.TextField(verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Entrevista',
                'verbose_name_plural': 'Entrevistas',
                'db_table': 'Entrevista',
            },
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=80, verbose_name='Nombre')),
                ('description', models.TextField(verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Encuesta',
                'verbose_name_plural': 'Encuesta',
                'db_table': 'Encuesta',
            },
        ),
        migrations.CreateModel(
            name='QuestionPoll',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=80, verbose_name='Nombre')),
                ('text', models.TextField(verbose_name='Texto de la pregunta')),
                ('answer', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Instruments.answer')),
                ('measurementCriterions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Metrics.measurementcriterion')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Instruments.poll')),
            ],
            options={
                'verbose_name': 'Pregunta de la Encuesta',
                'verbose_name_plural': 'Preguntas de la Encuesta',
                'db_table': 'PreguntaEncuesta',
            },
        ),
        migrations.CreateModel(
            name='QuestionInterview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=80, verbose_name='Nombre')),
                ('text', models.TextField(verbose_name='Texto de la pregunta')),
                ('answer', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Instruments.answer')),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Instruments.interview')),
                ('measurementCriterions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Metrics.measurementcriterion')),
            ],
            options={
                'verbose_name': 'Pregunta de la Entrevista',
                'verbose_name_plural': 'Preguntas de la Entrevista',
                'db_table': 'PreguntaEntrevista',
            },
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=80, verbose_name='Nombre')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('observationCriterions', models.ManyToManyField(to='Metrics.measurementcriterion')),
            ],
            options={
                'verbose_name': 'Observación',
                'verbose_name_plural': 'Observaciones',
                'db_table': 'Observación',
            },
        ),
    ]
