# Generated by Django 4.1.7 on 2023-06-04 18:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Metrics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=80, verbose_name='Nombre')),
                ('description', models.TextField(verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Entrevista',
                'verbose_name_plural': 'Entrevistas',
                'db_table': 'Entrevista',
            },
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=80, verbose_name='Nombre')),
                ('description', models.TextField(verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Observación',
                'verbose_name_plural': 'Observaciones',
                'db_table': 'Observación',
            },
        ),
        migrations.CreateModel(
            name='ObservationCriterions',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('measurementCriterions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Metrics.measurementcriterion')),
                ('observation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Instruments.observation')),
            ],
            options={
                'verbose_name': 'Criterio de Observacion',
                'verbose_name_plural': 'Criterios de Observacion',
                'db_table': 'CriterioObservacion',
            },
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=80, verbose_name='Nombre')),
                ('description', models.TextField(verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Encuesta',
                'verbose_name_plural': 'Encuesta',
                'db_table': 'Encuesta',
            },
        ),
        migrations.CreateModel(
            name='QuestionPoll',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=80, verbose_name='Nombre')),
                ('text', models.TextField(verbose_name='Texto de la pregunta')),
                ('measurementCriterions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Metrics.measurementcriterion')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Instruments.poll')),
            ],
            options={
                'verbose_name': 'Pregunta de la Encuesta',
                'verbose_name_plural': 'Preguntas de la Encuesta',
                'db_table': 'PreguntaEncuesta',
            },
        ),
        migrations.CreateModel(
            name='QuestionInterview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=80, verbose_name='Nombre')),
                ('text', models.TextField(verbose_name='Texto de la pregunta')),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Instruments.interview')),
                ('measurementCriterions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Metrics.measurementcriterion')),
            ],
            options={
                'verbose_name': 'Pregunta de la Entrevista',
                'verbose_name_plural': 'Preguntas de la Entrevista',
                'db_table': 'PreguntaEntrevista',
            },
        ),
        migrations.CreateModel(
            name='ObservationResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('value', models.IntegerField(default=0, verbose_name='Valor Obtenido')),
                ('observationCriterions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Instruments.observationcriterions')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Resultado de la Observacion',
                'verbose_name_plural': 'Resultados de las Observaciones',
                'db_table': 'ResultadoObservacion',
            },
        ),
        migrations.CreateModel(
            name='AnswerPoll',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('answer', models.TextField(max_length=255, verbose_name='Respuesta')),
                ('value', models.IntegerField(default=0, verbose_name='Valor Obtenido')),
                ('questionPoll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Instruments.questionpoll')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Respuesta Encuesta',
                'verbose_name_plural': 'Respuestas Encuesta',
                'db_table': 'RespuestaEncuesta',
            },
        ),
        migrations.CreateModel(
            name='AnswerInterview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('answer', models.TextField(max_length=255, verbose_name='Respuesta')),
                ('value', models.IntegerField(default=0, verbose_name='Valor Obtenido')),
                ('questionInterview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Instruments.questioninterview')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Respuesta Entrevista',
                'verbose_name_plural': 'Respuestas Entrevista',
                'db_table': 'RespuestaEntrevista',
            },
        ),
    ]
