# Generated by Django 4.1.7 on 2023-11-07 14:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Instruments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
