# Generated by Django 4.1.7 on 2023-11-15 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Instruments', '0003_interview_users_observation_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='observation',
            name='users',
        ),
    ]
