# Generated by Django 4.1.7 on 2023-11-20 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Instruments', '0004_remove_observation_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='anonymous',
            field=models.BooleanField(default=False, verbose_name='Anónimo'),
        ),
    ]
