# Generated by Django 4.1.7 on 2023-11-23 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Instruments', '0005_poll_anonymous'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='name',
            field=models.CharField(max_length=80, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='name',
            field=models.CharField(max_length=80, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='observationcriterions',
            name='criterion',
            field=models.TextField(max_length=255, unique=True, verbose_name='Criterio'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='name',
            field=models.CharField(max_length=80, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='questioninterview',
            name='name',
            field=models.CharField(max_length=80, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='questionpoll',
            name='name',
            field=models.CharField(max_length=80, unique=True, verbose_name='Nombre'),
        ),
    ]
