# Generated by Django 4.1.7 on 2023-11-25 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Metrics', '0007_alter_scale_scale_label'),
        ('Instruments', '0006_alter_interview_name_alter_observation_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionpoll',
            name='measurementCriterions',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Metrics.measurementcriterion'),
        ),
    ]
