# Generated by Django 4.1.7 on 2023-11-26 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Metrics', '0007_alter_scale_scale_label'),
        ('Instruments', '0007_alter_questionpoll_measurementcriterions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observationcriterions',
            name='measurementCriterions',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Metrics.measurementcriterion'),
        ),
        migrations.AlterField(
            model_name='questioninterview',
            name='measurementCriterions',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Metrics.measurementcriterion'),
        ),
    ]
